version: "3"
services:
  sample-angular:
    image: sample-angular-image
    container_name: sample-angular-container
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "ng serve --host=0.0.0.0"
    ports:
      - "4200:4200"
    volumes:
      - ./app:/app
    working_dir: /app/sample

  json-server:
    image: node:18-alpine
    container_name: json-server-container
    volumes:
      - ./app/sample/db.json:/data/db.json
    command: sh -c "npm install -g json-server && json-server --watch /data/db.json --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
